### PR TITLE
Update ErrorTranslator.php

### PR DESCRIPTION
**Pull request by rekrios**
bug: variable "$failed" overriden

### CODE REVIEW

**Comment by lindyhopchris** [comment]
So the build has failed because since I released the last version, they've renamed Laravel 5.9 to 6.0. I need to update that on master and then you can back merge. Will let you know when I've done that.

**Comment by rekrios** [comment]
> So the build has failed because since I released the last version, they've renamed Laravel 5.9 to 6.0. I need to update that on master and then you can back merge. Will let you know when I've done that.

thx, waiting for it

**Comment by lindyhopchris** [comment]
Can you back merge `hotfix/1.3.1` into your branch? That should fix the build problem.

**Comment by lindyhopchris** [comment]
BTW thanks for the PR, hadn't spotted this problem before now.

**Comment by rekrios** [comment]
i intended to use this functionality, so it's useful for both of us)

**Comment by lindyhopchris** [comment]
Just pushed the `1.3.1` tag, so should be available via Composer shortly.

**Pull request merged**
