### PR TITLE
[DOCS] Add basic rule example

### PR DESCRIPTION
**Pull request by GIANTCRAB**
This pull request will add useful information on how to setup a basic validation rule.

I was encountering issues on how to add validation for rules that are oneToMany eg: tags. Had to search the tests you had to find out how to do it.

Hopefully this will help other users.

### CODE REVIEW

**Comment by lindyhopchris** [comment]
Hi! Thanks for this. I don't think the `exists` rules are actually necessary. Because we check for compliance with the JSON API spec *before* the Laravel validation runs, we reject any resource identifiers that do not reference resources that exist.

Have you tried submitting IDs for tags that don't exist to see if they are rejected without your `exists` rules?

Bet yes think this would be useful to add to the docs... maybe just slightly amended. Will have a think about what the amendment could be.

**Comment by GIANTCRAB** [comment]
I've ran it without 'exists' and it seems like it is rejected - returns 404 error.

I'll remove exists rule and replace it with type check?

**Comment by lindyhopchris** [comment]
Yes, maybe remove the `exists` but add in a comment explaining that `exists` isn't necessary because we check that as part of validating the request complies with the JSON API spec? It sends a `404` in that instance because the spec says:

> A  server MUST return 404 Not Found when processing a request that references a related resource that does not exist.
https://jsonapi.org/format/#crud-creating

**Comment by GIANTCRAB** [comment]
Im on an overseas exercise atm, will do the amendments when I get back in 3
weeks.

Thanks.

**Comment by GIANTCRAB** [comment]
Hey Chris, 

I've added some information about that in the latest commit. Please review and let me know if further changes are required.

Thanks again!

**Comment by lindyhopchris** [comment]
Thanks!

**Pull request merged**
