### PR TITLE
[Feature] Accept other media types

### PR DESCRIPTION
**Pull request by lindyhopchris**
This feature improves content negotiation by allowing the client to specify other media types. See #221

It removes the `neomerx/json-api` codec matcher which we would have had to do when upgrading that package to `2.0` in the future. In its place it adds a `ContentNegotiatorInterface`. There is a default implementation in the package which is used in most cases, and consuming applications may not have to ever implement their own. However, it now allows either a named (multi-resource) content negotiator or a resource specific content negotiator to be implemented - like authorizers.

So far we've implemented allowing different Accept media types plus using resource-specific content negotiators. However, this is a work in progress and the following still needs to be done:

- [x] Allow different request content types.
- [x] Update the stub API config
- [x] Move applying the content negotiator middleware to the resource group as it is currently on the API group.
- [x] Allow a default named content negotiator to be set at the API level.
- [x] Allow a named (multi-resource) content negotiator for a resource.
- [x] Add content negotiator generators
- [x] Add a flag to the resource generator to generate a content negotiator at the same time.
- [x] Document it

This needs to be merged for `1.0` because if it doesn't go in then, it will have to wait until `2.0` as it has involved re-wiring a lot of the internals.

### CODE REVIEW

**Comment by jannis-a** [comment]
Would this allow having a mixed request with a json payload and file(s)? I'm currently working on an endpoint for media files and trying to figure out how to handle file uploads and a jsonapi payload for meta data.

**Comment by lindyhopchris** [comment]
Hi @jannis-a sorry for slow reply, got a crazy work deadline so been a bit busy!

So yes that would be good to support. What's the HTTP headers when a request has both JSON API payload plus files? I've never had to try that.

**Comment by jannis-a** [comment]
No problem @lindyhopchris :smile: 

Take a look at this discussion, there's an example of a request archiving this: https://github.com/yahoo/elide/issues/203

**Comment by lindyhopchris** [comment]
Note to self: would be good to solve #265 as part of this PR.

**Pull request merged**
