### PR TITLE
Fixed Api multiple binding

### PR DESCRIPTION
**Pull request by zlodes**
Environment: tests or Swoole.

When application loaded in memory we can do two (or more) http requests. On every request the `BootJsonApi` middleware creates new instances for `Api` class (and then for `Container`)...

We are inject new ResourceProviders from external packages and this `Api` and `Container` behavior breaks all.

It may be cause of any other bugs like a memory leak.

### CODE REVIEW

**Comment by lindyhopchris** [comment]
Hi. Thanks for this but it cannot be merged - it assumes that the request is for the same API as the previous request, which isn't necessarily true.

I don't support multiple HTTP requests in a single test because it's an incorrect testing style: there will be memory leaks between the mutiple requests because in HTTP a new Laravel application instance would get created for every HTTP request. This is not the case if you test two or more HTTP requests in a single test without resetting the application, so can lead to false positives or negatives.

As for Swoole I've never used that before but you'll also get memory leaks (not just from this package) if you reset the application.

As such I think it's the correct behaviour to always create a new API instance each time the boot middleware is hit, as it is effectively a new request. The bound API instance is only intended to be used for one HTTP request.

**Comment by lindyhopchris** [comment]
Meant to say, that comment above is meant as a discussion, feel free to let me know what you think!

**Comment by zlodes** [comment]
In some difficult cases we need to make multiple HTTP requests in one test.

Example:
We makes 2FA module based on JSON:API.
There are three resource types: `two-fa-provider`, `two-fa-settings` and `two-fa-verification`. 

We are using `AggregateResolver` afterResolving event for attach ResourceProviders from external package like this:
```php
/**
 * @param AbstractProvider $resourceProvider
 */
private function registerResolver(AbstractProvider $resourceProvider): void
{
    $this->app->afterResolving(
        AggregateResolver::class,
        static function (AggregateResolver $resolver) use ($resourceProvider) {
            $resolver->attach($resourceProvider->getResolver());
        }
    );
}
```

`laravel-json-api` is required by our `json-api` package that provides base classes like `Adapter`. It cause that we can not use configs for define external ResourceProviders. 

Another package (e.g. 2fa module) in their ServiceProvider calls `registerResolver` method.

The task is to write integration tests that will covers full 2FA cycle. 

1. GET /api/v1/two-fa-providers
2. POST /api/v1/two-fa-settings <- Got `No adapter for resource type: two-fa-settings` error here because `two-fa-settings` adapter stored in `Container` that was created in first HTTP request and was rewrited on second (current) HTTP request.
3. ...

That changes broke nothing, but `Container` and `Api` becomes to `Singleton` and developers will be able to make multiple HTTP requests in a tests.

Sorry for my english. 🌚

**Comment by zlodes** [comment]
Another trouble with multiple HTTP requests: `Route` singleton.
https://github.com/cloudcreativity/laravel-json-api/blob/d59c49ad502911062151837d057438837133ca89/src/ServiceProvider.php#L230


There are two requests `GET /api/v1/two-fa-providers` and `GET /api/v1/two-fa-settings`.

First:
image
Second: 
image

I think that json-api `Route` and Laravel Route classes must have same behavior.

It can be fixed with removing singleton section from ServiceProvider. I can create another PR for this.

**Comment by lindyhopchris** [comment]
Hi. I really cannot accept this PR. TLDR the problem is in your tests, not this package.

If you submit multiple HTTP requests in a single request, you'd have to submit a PR to every package you use removing the use of singletons throughout. In a *real* environment, every HTTP request gets a new instance of the Laravel application. So in reality the singleton only exists for the lifetime of a single HTTP request. It is therefore an invalid test to test two HTTP requests without resetting the application because evey singleton would exist across both requests, which means false positives or negatives can easily creep into your tests.

A good HTTP test will set the application state in the test state you expect it to be in for the scenario, then fire a single request against it and test that it handles it correctly. I.e. replicate a single instance of the Laravel application handling a single request.

So your test should be split in two. The second one should put the application in the state you'd expect it to be in when it receives the second request. For example, if it relied on something to be in the cache or session from a previous request, then your test should insert that into the cache or session, then test the request.

I'm happy to keep discussing this if you need help, but I cannot merge this into this package.

**Pull request closed without merging**
