### PR TITLE
Fix for methods in routes.

### PR DESCRIPTION
**Pull request by MCMatters**
Fix for methods in relationship routes. Add support of options "only" and "except" in resource routes

### CODE REVIEW

**Comment by lindyhopchris** [comment]
@MCMatters 

Thanks for the pull request and good spot on the bug. 

In terms of the "only" and "except" options, they're not strictly required. If you're using the `JsonApiController` then the controller will send `501 Not Implemented` responses if you haven't defined the methods required for the route that is being dispatched.

I think that's correct because the JSON API spec defines that all those routes should be available, so from the client's perspective the route should exist. So a `501` response would be semantically correct.

Do you have a use for `only` and `except` that I'm not thinking of?

**Comment by MCMatters** [comment]
Yes, you are right. I'm beginner in the Laravel and I thought that would be good to have this functional

**Comment by lindyhopchris** [comment]
No problem. Can you update the pull request so that the options aren't in there? Then I'll be able to merge it.

**Comment by MCMatters** [comment]
Yes, updated

**Pull request merged**
