### PR TITLE
Add docs for custom controller

### PR DESCRIPTION
**Pull request by GIANTCRAB**
Hi, I've added documentation on how to create a custom controller. The docs are based on information I've learnt through the demo app.

Also, could you take a little look at the `Update` part where I did a password check. I'm wondering if this can be done in the hydrator instead?

Please let me know if there are any issues with it.

Thank you!

### CODE REVIEW

**Comment by lindyhopchris** [comment]
Hi! Thanks for this. Yes, it looks along the right lines. There's actually an example custom controller in the demo app which yours generally follows:
https://github.com/cloudcreativity/demo-laravel-json-api/blob/5.4/app/Http/Controllers/Api/SitesController.php

Personally I would do the password stuff in the hydrator, but there's no reason you can't do it in the controller. I would get the new password from the resource the client provided, and then compare it against the existing one. Plus you need to use `Hash::check()` to do the comparison. I.e.:

```php
$newPassword = $resource->getAttributes()->get('password');
if (!Hash::check($newPassword, $record->password)) {
  $record->password = Hash::make($newPassword);
}
```

I'll merge this PR later - will probably make a few tiny amendments but it definitely can be merged.

**Comment by GIANTCRAB** [comment]
Okay! Got it! I'll fix this issue. There seem to also be `readRelatedResource` and `readRelationship`. I'll add those in too.

**Comment by lindyhopchris** [comment]
@GIANTCRAB ah, I'd just made changes and was about to merge. I'll merge now and then feel free to send another PR with some of the extra things you were planning on adding.

**Comment by GIANTCRAB** [comment]
Alright. @lindyhopchris one question -- would `readRelatedResource` and `readRelationship` fall under eloquent or custom controller?

**Pull request merged**
