### PR TITLE
[Feature] Finalise test helpers for 1.0

### PR DESCRIPTION
**Pull request by lindyhopchris**
This commit finalises the test helpers ready for the `1.0` release. The new test assertions provide significantly better PHPUnit output when they fail.

Also tidied up the test response class, as the method names were starting to get quite inconsistent and unpredictable. Methods that were marked as deprecated have been removed, and those that were not marked as deprecated have now been marked as deprecated for 2.0.

### CODE REVIEW

**Comment by jannis-a** [comment]
Is there anything to do besides checking for the usage of the deprecated/removed methods? Because with the new version a lot of my tests fail with the following error (lines differ):

`Error : Class 'CloudCreativity\JsonApi\Testing\DocumentTester' not found
 /home/jannis/work/backend/mod-base/vendor/cloudcreativity/laravel-json-api/src/Testing/TestResponse.php:134
 /home/jannis/work/backend/mod-base/vendor/cloudcreativity/laravel-json-api/src/Testing/TestResponse.php:292
 /home/jannis/work/backend/mod-base/vendor/cloudcreativity/laravel-json-api/src/Testing/TestResponse.php:307
 /home/jannis/work/backend/mod-base/tests/Feature/JsonApi/Web/UsersTest.php:83`

**Comment by lindyhopchris** [comment]
You'll need to update the dev dependency as well as that class doesn't exist any more. There's some upgrade notes here:
https://github.com/cloudcreativity/laravel-json-api/blob/develop/docs/upgrade.md

I.e. follow the upgrade notes for `1.0.0-beta.6`.

Let me know if that solves it because if it doesn't I'll need to amend the upgrade notes.

**Comment by jannis-a** [comment]
@lindyhopchris I followed the upgrade guide, removed the json-api-testing package and installed it again with version `^1.0`. According to `composer info` I have version `1.x-dev c973e12` installed but the error still occurs.

**Comment by lindyhopchris** [comment]
`DocumentTester` does not appear anywhere in the code base so this is some sort of composer issue. Out of interest, do you do a Composer install with an optimized autoloader?

Try `composer dump-autoload` and then re-run the tests.

**Comment by jannis-a** [comment]
I had the wrong version of the library itself installed. I was on beta5, installing `dev-develop` fixed the error. I thought those changes were already tagged as a new release. :)

**Comment by lindyhopchris** [comment]
Ah no problem! No haven't tagged them yet. There's a chance the next tag might be `1.0.0-rc1`!

**Pull request merged**
